Neste notebook, será feita uma rede neural para classificar plantas em suas determinadas classes baseadas no treinamento em cima de um dataset delas

In [1]:
from sklearn import datasets
iris = datasets.load_iris()

iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

iris é composto por três campos: target, data, e feature_names.

Data contém entradas do dataset com dados sobre 150 plantas

In [2]:
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

Target contém 3 classes de planta, cada uma das 150 plantas em data, está associada a uma das 3 classes em target.

In [3]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

feature_names contém informações sobre o que é cada um dos 4 campos em cada uma das 150 entradas na database

In [4]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

Primeiro pega-se os inputs da rede neural:

In [5]:
X = iris.data

X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

Depois pega-se os outputs da rede neural:

In [6]:
Y = iris.target

Y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

Logo em seguida, aplica-se um pre processamento em cima de X, para padronizar ele deixando-o numa escala distribuida normalmente entre 0 e 1

In [7]:
from sklearn.preprocessing import StandardScaler

scaler_x = StandardScaler()
X = scaler_x.fit_transform(X)

X

array([[-9.00681170e-01,  1.01900435e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00, -1.31979479e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.38535265e+00,  3.28414053e-01, -1.39706395e+00,
        -1.31544430e+00],
       [-1.50652052e+00,  9.82172869e-02, -1.28338910e+00,
        -1.31544430e+00],
       [-1.02184904e+00,  1.24920112e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-5.37177559e-01,  1.93979142e+00, -1.16971425e+00,
        -1.05217993e+00],
       [-1.50652052e+00,  7.88807586e-01, -1.34022653e+00,
        -1.18381211e+00],
       [-1.02184904e+00,  7.88807586e-01, -1.28338910e+00,
        -1.31544430e+00],
       [-1.74885626e+00, -3.62176246e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00,  9.82172869e-02, -1.28338910e+00,
        -1.44707648e+00],
       [-5.37177559e-01,  1.47939788e+00, -1.28338910e+00,
        -1.31544430e+00],
       [-1.26418478e+00,  7.88807586e-01, -1.22655167e+00,
      

A seguir, faz-se One hot encoding para que cada entrada em Y, tenha 3 campos, o mesmo número de neuronios na camada de saída da rede neural (Já que existem 3 classes possíveis)

In [8]:
from sklearn.preprocessing import OneHotEncoder

onehot = OneHotEncoder(sparse_output=False)

#Reshape de Y de (150, ) (1D) para (150, 1) (2D) para o OneHotEncoder que espera uma entrada 2D
y = Y.reshape(-1, 1)
y.shape

(150, 1)

In [9]:
y = onehot.fit_transform(y)
y

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

Cada classe foi codificada com um código único por classe (três códigos únicos)

A classe 0 foi codificada como [1, 0, 0],

a classe 1 foi codificada como [0, 1, 0]

e a classe 2 foi codificada como [0, 0, 1].

Assim, a ultima camada composta de 3 neuronios pode outputar qual classe cada entrada em X pertence á.

Faz-se agora a divisão dos dados entre treinamento e teste (70% para treinamento, e 30% para teste):

A divisão é feita aleatóriamente

In [10]:
from sklearn.model_selection import train_test_split

X_treinamento, X_teste, y_treinamento, y_teste = train_test_split(X, y, test_size = 0.3)

print(X_treinamento)
print(y_treinamento)
print(X_teste)
print(y_teste)


[[-9.00681170e-01  1.70959465e+00 -1.05603939e+00 -1.05217993e+00]
 [-1.73673948e-01  1.70959465e+00 -1.16971425e+00 -1.18381211e+00]
 [-1.14301691e+00 -1.31979479e-01 -1.34022653e+00 -1.31544430e+00]
 [ 2.24968346e+00 -1.31979479e-01  1.33113254e+00  1.44883158e+00]
 [ 2.49201920e+00  1.70959465e+00  1.50164482e+00  1.05393502e+00]
 [-1.26418478e+00  7.88807586e-01 -1.05603939e+00 -1.31544430e+00]
 [-1.02184904e+00  7.88807586e-01 -1.22655167e+00 -1.05217993e+00]
 [ 1.89829664e-01 -1.97355361e+00  1.37546573e-01 -2.62386821e-01]
 [-1.14301691e+00 -1.51316008e+00 -2.60315415e-01 -2.62386821e-01]
 [ 1.28034050e+00  9.82172869e-02  7.62758269e-01  1.44883158e+00]
 [ 6.74501145e-01  9.82172869e-02  9.90107977e-01  7.90670654e-01]
 [-5.37177559e-01  7.88807586e-01 -1.16971425e+00 -1.31544430e+00]
 [-1.73673948e-01 -5.92373012e-01  1.94384000e-01  1.32509732e-01]
 [ 6.86617933e-02  3.28414053e-01  5.92245988e-01  7.90670654e-01]
 [ 2.24968346e+00 -5.92373012e-01  1.67215710e+00  1.05393502e

In [11]:
print(X_treinamento.shape)
print(X_teste.shape)

(105, 4)
(45, 4)


Agora começa-se a definir a rede neural:

In [12]:
import tensorflow as tf
import numpy as np

2026-02-09 15:46:46.204065: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-02-09 15:46:46.212687: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1770662806.232780   20441 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1770662806.240083   20441 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2026-02-09 15:46:46.256476: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instr

A rede terá 4 neuronios de entrada, um para cada campo de X, as entradas da rede.

Terá 3 neuronios de saída, cada um representando a probabilidade de a entrada pertencer a uma das 3 classes.

Terá uma camada oculta, já que uma já é o suficiente para resolver este problema, com o número de neuronios determinado pela formula:

(neuronios_entrada + neuronios_saida)/2, arredondando para cima caso necessário

In [13]:
neuronios_entrada = X.shape[1]
neuronios_saida = y.shape[1]
neuronios_oculta = int(np.ceil((X.shape[1] + y.shape[1])/2))

print(X.shape[1])
print(y.shape[1])

neuronios_oculta

4
3


4

Define-se o dicionário com os pesos de cada camada, e o dicionário dos biases de cada camada

OBS: oculta são os pesos que ficam entre a camada de entrada e a oculta, e saida são os pesos que ficam entre a camada oculta e a de saída.

oculta: Uma matriz 4 x 4 (16 pesos) aonde cada linha está associada ao peso de cada um dos 4 neuronios de entrada, para cada um dos 4 neuronios da camada oculta.

saída: Uma matrix 4x3 (12 pesos) aonde cada linha está associada ao peso de cada um dos 4 neuronios da camada oculta, para cada um dos 3 neuronios da camada de saída.

In [14]:
W = {"oculta": tf.Variable(tf.random.normal([neuronios_entrada, neuronios_oculta])),
     "saida": tf.Variable(tf.random.normal([neuronios_oculta, neuronios_saida]))}

W

2026-02-09 15:46:47.948649: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:47] Overriding orig_value setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
I0000 00:00:1770662807.948708   20441 gpu_device.cc:2022] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 3617 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3050 6GB Laptop GPU, pci bus id: 0000:01:00.0, compute capability: 8.6


{'oculta': <tf.Variable 'Variable:0' shape=(4, 4) dtype=float32, numpy=
 array([[ 0.6694615 , -0.45171836,  0.12798685,  1.1586668 ],
        [ 0.10974334,  0.20490429,  0.6124314 ,  1.6056187 ],
        [ 1.637075  , -1.6852276 , -0.83629954, -1.2335958 ],
        [ 0.80845183, -2.5176117 ,  1.2037961 ,  0.51143044]],
       dtype=float32)>,
 'saida': <tf.Variable 'Variable:0' shape=(4, 3) dtype=float32, numpy=
 array([[ 0.4808048 , -0.7328789 ,  0.07843399],
        [-1.8855284 , -1.2474447 ,  1.0641471 ],
        [-1.5046955 , -0.47776544, -1.1076941 ],
        [-0.420014  , -0.1702173 ,  0.44105953]], dtype=float32)>}

Bias:

oculta: um vetor de 4 posições (ou matriz 4x1),
cada uma das 4 bias é a bias de um dos 4 neuronios da camada oculta

saída: um vetor de 3 posições (ou matriz 3x1),
cada uma das 3 bias é a bias de um dos 3 neuronios da camada de saída

In [15]:
b = {"oculta": tf.Variable(tf.random.normal([neuronios_oculta])),
     "saida": tf.Variable(tf.random.normal([neuronios_saida]))}

b

{'oculta': <tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([ 0.62759113, -0.30210155, -0.4159715 , -0.0135704 ], dtype=float32)>,
 'saida': <tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([ 0.96414   , -1.2220048 ,  0.27127337], dtype=float32)>}

Converte-se o dataset para tensores para poder ser usado pelo tensorflow que espera trabalhar com tensores ou numpy arrays.

In [16]:
X_treinamento = tf.convert_to_tensor(X_treinamento, dtype = tf.float32, name = 'X')
y_treinamento = tf.convert_to_tensor(y_treinamento, dtype = tf.float32, name = 'y')
X_teste = tf.convert_to_tensor(X_teste, dtype = tf.float32, name = 'X')
y_teste = tf.convert_to_tensor(y_teste, dtype = tf.float32, name = 'y')

print(X_treinamento)
print(y_treinamento)
print(X_teste)
print(y_teste)

tf.Tensor(
[[-9.0068120e-01  1.7095946e+00 -1.0560393e+00 -1.0521799e+00]
 [-1.7367394e-01  1.7095946e+00 -1.1697142e+00 -1.1838121e+00]
 [-1.1430169e+00 -1.3197948e-01 -1.3402265e+00 -1.3154444e+00]
 [ 2.2496834e+00 -1.3197948e-01  1.3311325e+00  1.4488316e+00]
 [ 2.4920192e+00  1.7095946e+00  1.5016448e+00  1.0539351e+00]
 [-1.2641848e+00  7.8880757e-01 -1.0560393e+00 -1.3154444e+00]
 [-1.0218490e+00  7.8880757e-01 -1.2265517e+00 -1.0521799e+00]
 [ 1.8982966e-01 -1.9735537e+00  1.3754657e-01 -2.6238683e-01]
 [-1.1430169e+00 -1.5131601e+00 -2.6031542e-01 -2.6238683e-01]
 [ 1.2803406e+00  9.8217286e-02  7.6275826e-01  1.4488316e+00]
 [ 6.7450112e-01  9.8217286e-02  9.9010795e-01  7.9067063e-01]
 [-5.3717756e-01  7.8880757e-01 -1.1697142e+00 -1.3154444e+00]
 [-1.7367394e-01 -5.9237301e-01  1.9438399e-01  1.3250974e-01]
 [ 6.8661794e-02  3.2841405e-01  5.9224600e-01  7.9067063e-01]
 [ 2.2496834e+00 -5.9237301e-01  1.6721570e+00  1.0539351e+00]
 [ 7.9566902e-01 -1.3197948e-01  8.1959569e-

Define-se o modelo da rede neural atravez da função mlp:

OBS: Usa-se a função relu pois não se quer trabalhar com números negativos (Ver por que)

OBS2: Softmax não é aplicado na ultima camada, pois a função erro já aplica ela.

In [17]:
@tf.function
def mlp(X, W, b):
    camada_oculta_entrada = tf.add(tf.matmul(X, W["oculta"]), b["oculta"])
    camada_oculta_ativacao = tf.nn.relu(camada_oculta_entrada)
    camada_saida_entrada = tf.add(tf.matmul(camada_oculta_ativacao, W["saida"]), b["saida"])
    return camada_saida_entrada

Exemplo do treinamento de uma época:

Utiliza-se o otimizador Adam, que tende a ser melhor do que a descida do gradiente simples

In [18]:
var_list = [W['oculta'], W['saida'], b['oculta'], b['saida']]
otimizador = tf.keras.optimizers.Adam(learning_rate = 0.0001)
erro_medio = 0.0
with tf.GradientTape() as tape:
    model = mlp(X_treinamento, W, b)
    error = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(labels = y_treinamento, logits = model))
gradientes = tape.gradient(error, var_list)
otimizador.apply_gradients(zip(gradientes, var_list))
erro_medio += error.numpy()

erro_medio

np.float32(7.810351)

Utilizaremos batch size = 8, ou seja, a rede treinara de 8 em 8 registros em X_treinamento

(Passa 8 registros, faz as atualizações dos pesos, passa mais 8, etc...)

São 13 batches de 8 registros cada

In [19]:
batch_size = 8
num_batches = int(len(X_treinamento) / batch_size)

num_batches

13

Agora utiliza-se a função np.array_split para separar os registros do dataset em num_batches arrays (13 arrays), cada um com o mesmo número de registros (8 registros), com exeção do primeiro array que tem 9 registros, pois o numero de registros em X_treinamento e y_treinamento não é divisivel por 8.

In [20]:
X_batches = np.array_split(X_treinamento, num_batches)
y_batches = np.array_split(y_treinamento, num_batches)

In [21]:
X_batches

[array([[-0.9006812 ,  1.7095946 , -1.0560393 , -1.0521799 ],
        [-0.17367394,  1.7095946 , -1.1697142 , -1.1838121 ],
        [-1.1430169 , -0.13197948, -1.3402265 , -1.3154444 ],
        [ 2.2496834 , -0.13197948,  1.3311325 ,  1.4488316 ],
        [ 2.4920192 ,  1.7095946 ,  1.5016448 ,  1.053935  ],
        [-1.2641848 ,  0.7888076 , -1.0560393 , -1.3154444 ],
        [-1.021849  ,  0.7888076 , -1.2265517 , -1.0521799 ],
        [ 0.18982966, -1.9735537 ,  0.13754657, -0.26238683],
        [-1.1430169 , -1.5131601 , -0.26031542, -0.26238683]],
       dtype=float32),
 array([[ 1.2803406 ,  0.09821729,  0.76275826,  1.4488316 ],
        [ 0.6745011 ,  0.09821729,  0.99010795,  0.79067063],
        [-0.53717756,  0.7888076 , -1.1697142 , -1.3154444 ],
        [-0.17367394, -0.592373  ,  0.194384  ,  0.13250974],
        [ 0.06866179,  0.32841405,  0.592246  ,  0.79067063],
        [ 2.2496834 , -0.592373  ,  1.672157  ,  1.053935  ],
        [ 0.795669  , -0.13197948,  0.8195957 

In [22]:
y_batches

[array([[1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [0., 0., 1.],
        [0., 0., 1.],
        [1., 0., 0.],
        [1., 0., 0.],
        [0., 1., 0.],
        [0., 1., 0.]], dtype=float32),
 array([[0., 0., 1.],
        [0., 0., 1.],
        [1., 0., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [0., 0., 1.],
        [0., 0., 1.]], dtype=float32),
 array([[1., 0., 0.],
        [0., 0., 1.],
        [1., 0., 0.],
        [0., 0., 1.],
        [0., 1., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [0., 1., 0.]], dtype=float32),
 array([[0., 1., 0.],
        [1., 0., 0.],
        [0., 0., 1.],
        [0., 1., 0.],
        [1., 0., 0.],
        [0., 0., 1.],
        [0., 0., 1.],
        [1., 0., 0.]], dtype=float32),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [1., 0., 0.],
        [0., 0., 1.],
        [0., 1., 0.],
        [0., 0., 1.],
        [1., 0., 0.],
        [0., 1., 0.]], dtype=float32),
 array([[0., 

Agora faz-se o treinamento

OBS: zip(A, B) junta cada elemento de A e B em pares para serem iterados.

In [23]:
@tf.function
def train_step(x_batch, y_batch):
    with tf.GradientTape() as tape:
        logits = mlp(x_batch, W, b)
        loss = tf.reduce_mean(
            tf.nn.softmax_cross_entropy_with_logits(labels=y_batch, logits=logits)
        )
    grads = tape.gradient(loss, var_list)
    otimizador.apply_gradients(zip(grads, var_list))
    
    return loss

In [ ]:
epochs = 3000

var_list = [W['oculta'], W['saida'], b['oculta'], b['saida']]
otimizador = tf.keras.optimizers.Adam(learning_rate = 0.0001)

for epoch in range(epochs):
    erro_medio = 0.0
    for i in range(num_batches):
        X_batch, y_batch = X_batches[i], y_batches[i]
        loss = train_step(X_batch, y_batch)
        erro_medio += loss
    
    erro_medio = erro_medio / num_batches
    if epoch % 500 == 0:
        print('Época: ' + str((epoch + 1)) + ' erro medio: ' + str(float(erro_medio.numpy())) + ' erros: ' + str(float(loss.numpy())))


Época: 1 erro medio: 7.780187606811523 erros: 8.315701484680176
Época: 501 erro medio: 2.0736374855041504 erros: 2.5622706413269043
Época: 1001 erro medio: 0.5087772607803345 erros: 0.6269733905792236
Época: 1501 erro medio: 0.20389612019062042 erros: 0.2105327844619751
Época: 2001 erro medio: 0.08701661974191666 erros: 0.0745866447687149
Época: 2501 erro medio: 0.05429349094629288 erros: 0.037893250584602356


Com os pesos e biases já treinados, veremos como eles foram modificados em relação aos seus valores originais nas primeiras celulas:

In [25]:
W

{'oculta': <tf.Variable 'Variable:0' shape=(4, 4) dtype=float32, numpy=
 array([[ 0.2538714 ,  0.02157961,  0.3228236 ,  1.6488256 ],
        [-0.00512253,  0.06263603, -0.7656702 ,  2.0428972 ],
        [ 2.1066854 , -1.5580488 , -0.11636433, -1.0161381 ],
        [ 2.0222886 , -2.37082   ,  1.1870494 ,  0.42437196]],
       dtype=float32)>,
 'saida': <tf.Variable 'Variable:0' shape=(4, 3) dtype=float32, numpy=
 array([[-1.5406693 , -1.429495  ,  1.6463362 ],
        [ 0.31730705, -2.777748  , -1.0878932 ],
        [-3.8619492 ,  0.19091019, -0.58274424],
        [ 0.31738952,  0.57887065, -0.5563187 ]], dtype=float32)>}

In [26]:
b

{'oculta': <tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([-0.74642926, -0.8964521 ,  1.8434738 ,  0.7640531 ], dtype=float32)>,
 'saida': <tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([ 2.062576 ,  0.8030756, -1.8772041], dtype=float32)>}

Agora faz-se testes com a rede neural já treinada para que ela possa classificar novos registros que ela nunca viu no treino:

In [28]:
previsoes_teste = mlp(X_teste, W, b)
previsoes_teste

<tf.Tensor: shape=(45, 3), dtype=float32, numpy=
array([[-1.86127987e+01, -4.34313965e+00,  2.86332798e+00],
       [ 3.59818029e+00, -1.26398087e+01, -7.14205217e+00],
       [ 4.13130569e+00, -1.00404806e+01, -7.81877089e+00],
       [ 4.03220224e+00, -9.46221352e+00, -7.52482176e+00],
       [ 3.93104267e+00, -1.00601025e+01, -7.41299677e+00],
       [-1.91978531e+01, -4.21329403e+00,  2.92943525e+00],
       [ 4.05001163e+00, -9.14127636e+00, -7.51034164e+00],
       [ 3.86680317e+00, -1.01684885e+01, -7.29900837e+00],
       [-1.17497902e+01, -1.23084688e+00, -5.71382761e-01],
       [-2.65061684e+01, -6.93728590e+00,  5.38755369e+00],
       [ 3.49533629e+00, -1.17394972e+01, -6.78944969e+00],
       [-1.20924416e+01, -2.90711939e-01, -1.77508545e+00],
       [-7.67643261e+00,  5.83972871e-01, -2.47260356e+00],
       [-9.84302235e+00,  1.39161253e+00, -3.67368507e+00],
       [ 5.44300747e+00, -8.54601574e+00, -1.02601538e+01],
       [-1.97867413e+01, -4.49108601e+00,  2.802093

Utiliza-se softmax na ultima camada para converte-la em um vetor de probabilidades, cada um dos 3 neuronios terá uma probabilidade associada a entrada ser de uma das 3 classes do dataset.

In [29]:
previsoes_teste = tf.nn.softmax(previsoes_teste)
previsoes_teste

<tf.Tensor: shape=(45, 3), dtype=float32, numpy=
array([[4.70667560e-10, 7.41222990e-04, 9.99258816e-01],
       [9.99978185e-01, 8.86995366e-08, 2.16554308e-05],
       [9.99992847e-01, 7.00274484e-07, 6.45868840e-06],
       [9.99989033e-01, 1.37862185e-06, 9.56849181e-06],
       [9.99987364e-01, 8.38913934e-07, 1.18396974e-05],
       [2.45412884e-10, 7.89966842e-04, 9.99210000e-01],
       [9.99988556e-01, 1.86677278e-06, 9.53668405e-06],
       [9.99984980e-01, 8.02682393e-07, 1.41495666e-05],
       [9.20985713e-06, 3.40856850e-01, 6.59133971e-01],
       [1.40841420e-14, 4.44005445e-06, 9.99995589e-01],
       [9.99965668e-01, 2.41869373e-07, 3.41475206e-05],
       [6.10735015e-06, 8.15227270e-01, 1.84766591e-01],
       [2.46875192e-04, 9.54829872e-01, 4.49233018e-02],
       [1.31256829e-05, 9.93714511e-01, 6.27235789e-03],
       [9.99999046e-01, 8.40705695e-07, 1.51427002e-07],
       [1.54702876e-10, 6.79699355e-04, 9.99320269e-01],
       [9.99981165e-01, 5.72855242e-07,

Agora normalizamos as saídas probabilisticas para que cada output da rede neural (Um array de 3 probabilidades), seja normalizado para o valor 0 1 2 representando uma das 3 classes possíveis:

A função abaixo funciona pegando o indice da maior probabilidade em cada registro (um valor por coluna pelo segundo parametro), isso é a mesma forma como as classes foram definidas, como números de 0 a 2.

In [30]:
previsoes_teste = tf.argmax(previsoes_teste, axis = 1).numpy()
previsoes_teste

array([2, 0, 0, 0, 0, 2, 0, 0, 2, 2, 0, 1, 1, 1, 0, 2, 0, 0, 1, 0, 2, 2,
       0, 2, 1, 2, 0, 1, 1, 2, 1, 0, 2, 1, 1, 1, 1, 2, 2, 2, 2, 1, 1, 2,
       2])

Fazemos a mesma coisa com y_teste para fins de comparação:

In [32]:
y_teste2 = tf.argmax(y_teste, axis = 1).numpy()
y_teste2

array([2, 0, 0, 0, 0, 2, 0, 0, 2, 2, 0, 2, 1, 1, 0, 2, 0, 0, 1, 0, 1, 2,
       0, 2, 1, 2, 0, 1, 1, 2, 2, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 1, 1, 2,
       2])

Por fim, medimos a taxa de acerto:

In [35]:
from sklearn.metrics import accuracy_score
taxa_acerto = accuracy_score(y_teste2, previsoes_teste)
taxa_acerto*100

print("A taxa de acerto é de: "+ str(taxa_acerto*100) + "%.")

A taxa de acerto é de: 91.11111111111111%.
