Neste notebook, será feita uma rede neural para classificar plantas em suas determinadas classes baseadas no treinamento em cima de um dataset delas

In [2]:
from sklearn import datasets
iris = datasets.load_iris()

iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

iris é composto por três campos: target, data, e feature_names.

Data contém entradas do dataset com dados sobre 150 plantas

In [3]:
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

Target contém 3 classes de planta, cada uma das 150 plantas em data, está associada a uma das 3 classes em target.

In [4]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

feature_names contém informações sobre o que é cada um dos 4 campos em cada uma das 150 entradas na database

In [5]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

Primeiro pega-se os inputs da rede neural:

In [6]:
X = iris.data

X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

Depois pega-se os outputs da rede neural:

In [7]:
Y = iris.target

Y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

Logo em seguida, aplica-se um pre processamento em cima de X, para padronizar ele deixando-o numa escala distribuida normalmente entre 0 e 1

In [8]:
from sklearn.preprocessing import StandardScaler

scaler_x = StandardScaler()
X = scaler_x.fit_transform(X)

X

array([[-9.00681170e-01,  1.01900435e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00, -1.31979479e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.38535265e+00,  3.28414053e-01, -1.39706395e+00,
        -1.31544430e+00],
       [-1.50652052e+00,  9.82172869e-02, -1.28338910e+00,
        -1.31544430e+00],
       [-1.02184904e+00,  1.24920112e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-5.37177559e-01,  1.93979142e+00, -1.16971425e+00,
        -1.05217993e+00],
       [-1.50652052e+00,  7.88807586e-01, -1.34022653e+00,
        -1.18381211e+00],
       [-1.02184904e+00,  7.88807586e-01, -1.28338910e+00,
        -1.31544430e+00],
       [-1.74885626e+00, -3.62176246e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00,  9.82172869e-02, -1.28338910e+00,
        -1.44707648e+00],
       [-5.37177559e-01,  1.47939788e+00, -1.28338910e+00,
        -1.31544430e+00],
       [-1.26418478e+00,  7.88807586e-01, -1.22655167e+00,
      

A seguir, faz-se One hot encoding para que cada entrada em Y, tenha 3 campos, o mesmo número de neuronios na camada de saída da rede neural (Já que existem 3 classes possíveis)

In [9]:
from sklearn.preprocessing import OneHotEncoder

onehot = OneHotEncoder(sparse_output=False)

#Reshape de Y de (150, ) (1D) para (150, 1) (2D) para o OneHotEncoder que espera uma entrada 2D
y = Y.reshape(-1, 1)
y.shape

(150, 1)

In [10]:
y = onehot.fit_transform(y)
y

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

Cada classe foi codificada com um código único por classe (três códigos únicos)

A classe 0 foi codificada como [1, 0, 0],

a classe 1 foi codificada como [0, 1, 0]

e a classe 2 foi codificada como [0, 0, 1].

Assim, a ultima camada composta de 3 neuronios pode outputar qual classe cada entrada em X pertence á.

Faz-se agora a divisão dos dados entre treinamento e teste (70% para treinamento, e 30% para teste):

A divisão é feita aleatóriamente

In [11]:
from sklearn.model_selection import train_test_split

X_treinamento, X_teste, y_treinamento, y_teste = train_test_split(X, y, test_size = 0.3)

print(X_treinamento)
print(y_treinamento)
print(X_teste)
print(y_teste)


[[ 1.89829664e-01 -8.22569778e-01  7.62758269e-01  5.27406285e-01]
 [-5.37177559e-01  7.88807586e-01 -1.16971425e+00 -1.31544430e+00]
 [ 1.64384411e+00  1.24920112e+00  1.33113254e+00  1.71209594e+00]
 [ 1.28034050e+00  9.82172869e-02  9.33270550e-01  1.18556721e+00]
 [-1.73673948e-01 -1.05276654e+00 -1.46640561e-01 -2.62386821e-01]
 [ 7.95669016e-01 -5.92373012e-01  4.78571135e-01  3.95774101e-01]
 [ 2.24968346e+00 -1.05276654e+00  1.78583195e+00  1.44883158e+00]
 [-1.73673948e-01 -5.92373012e-01  1.94384000e-01  1.32509732e-01]
 [-1.02184904e+00  1.24920112e+00 -1.34022653e+00 -1.31544430e+00]
 [-4.16009689e-01 -1.05276654e+00  3.64896281e-01  8.77547895e-04]
 [-1.50652052e+00  1.24920112e+00 -1.56757623e+00 -1.31544430e+00]
 [-4.16009689e-01 -1.51316008e+00 -3.29657076e-02 -2.62386821e-01]
 [-1.14301691e+00 -1.51316008e+00 -2.60315415e-01 -2.62386821e-01]
 [ 9.16836886e-01 -1.31979479e-01  3.64896281e-01  2.64141916e-01]
 [-9.00681170e-01  1.01900435e+00 -1.34022653e+00 -1.31544430e

In [12]:
print(X_treinamento.shape)
print(X_teste.shape)

(105, 4)
(45, 4)


Agora começa-se a definir a rede neural:

In [13]:
import tensorflow as tf
import numpy as np

A rede terá 4 neuronios de entrada, um para cada campo de X, as entradas da rede.

Terá 3 neuronios de saída, cada um representando a probabilidade de a entrada pertencer a uma das 3 classes.

Terá uma camada oculta, já que uma já é o suficiente para resolver este problema, com o número de neuronios determinado pela formula:

(neuronios_entrada + neuronios_saida)/2, arredondando para cima caso necessário

In [14]:
neuronios_entrada = X.shape[1]
neuronios_saida = y.shape[1]
neuronios_oculta = int(np.ceil((X.shape[1] + y.shape[1])/2))

print(X.shape[1])
print(y.shape[1])

neuronios_oculta

4
3


4

Define-se o dicionário com os pesos de cada camada, e o dicionário dos biases de cada camada

OBS: oculta são os pesos que ficam entre a camada de entrada e a oculta, e saida são os pesos que ficam entre a camada oculta e a de saída.

oculta: Uma matriz 4 x 4 (16 pesos) aonde cada linha está associada ao peso de cada um dos 4 neuronios de entrada, para cada um dos 4 neuronios da camada oculta.

saída: Uma matrix 4x3 (12 pesos) aonde cada linha está associada ao peso de cada um dos 4 neuronios da camada oculta, para cada um dos 3 neuronios da camada de saída.

In [15]:
W = {"oculta": tf.Variable(tf.random.normal([neuronios_entrada, neuronios_oculta])),
     "saida": tf.Variable(tf.random.normal([neuronios_oculta, neuronios_saida]))}

W

{'oculta': <tf.Variable 'Variable:0' shape=(4, 4) dtype=float32, numpy=
 array([[ 0.9517245 ,  1.0661638 ,  0.41351327, -0.18104367],
        [ 0.45837978, -0.43584406, -0.5536841 , -0.41765255],
        [ 0.46330437, -0.02503938,  1.1179261 , -0.5752433 ],
        [-0.67961043, -0.47042608,  1.0953274 ,  0.63117754]],
       dtype=float32)>,
 'saida': <tf.Variable 'Variable:0' shape=(4, 3) dtype=float32, numpy=
 array([[ 1.75926   , -0.2698888 , -1.0381978 ],
        [ 0.668828  ,  1.164829  ,  0.06216246],
        [ 0.8343063 , -0.15716682, -0.17383297],
        [-0.9320182 ,  0.32327098, -0.4322818 ]], dtype=float32)>}

Bias:

oculta: um vetor de 4 posições (ou matriz 4x1),
cada uma das 4 bias é a bias de um dos 4 neuronios da camada oculta

saída: um vetor de 3 posições (ou matriz 3x1),
cada uma das 3 bias é a bias de um dos 3 neuronios da camada de saída

In [16]:
b = {"oculta": tf.Variable(tf.random.normal([neuronios_oculta])),
     "saida": tf.Variable(tf.random.normal([neuronios_saida]))}

b

{'oculta': <tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([-0.38043705,  0.10814247,  0.3476631 , -0.06573395], dtype=float32)>,
 'saida': <tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([ 0.07572637, -2.2057185 , -1.4619238 ], dtype=float32)>}

Converte-se o dataset para tensores para poder ser usado pelo tensorflow que espera trabalhar com tensores ou numpy arrays.

In [17]:
X_treinamento = tf.convert_to_tensor(X_treinamento, dtype = tf.float32, name = 'X')
y_treinamento = tf.convert_to_tensor(y_treinamento, dtype = tf.float32, name = 'y')
X_teste = tf.convert_to_tensor(X_teste, dtype = tf.float32, name = 'X')
y_teste = tf.convert_to_tensor(y_teste, dtype = tf.float32, name = 'y')

print(X_treinamento)
print(y_treinamento)
print(X_teste)
print(y_teste)

tf.Tensor(
[[ 1.8982966e-01 -8.2256979e-01  7.6275826e-01  5.2740628e-01]
 [-5.3717756e-01  7.8880757e-01 -1.1697142e+00 -1.3154444e+00]
 [ 1.6438441e+00  1.2492011e+00  1.3311325e+00  1.7120960e+00]
 [ 1.2803406e+00  9.8217286e-02  9.3327057e-01  1.1855673e+00]
 [-1.7367394e-01 -1.0527666e+00 -1.4664055e-01 -2.6238683e-01]
 [ 7.9566902e-01 -5.9237301e-01  4.7857115e-01  3.9577410e-01]
 [ 2.2496834e+00 -1.0527666e+00  1.7858319e+00  1.4488316e+00]
 [-1.7367394e-01 -5.9237301e-01  1.9438399e-01  1.3250974e-01]
 [-1.0218490e+00  1.2492011e+00 -1.3402265e+00 -1.3154444e+00]
 [-4.1600969e-01 -1.0527666e+00  3.6489627e-01  8.7754789e-04]
 [-1.5065205e+00  1.2492011e+00 -1.5675763e+00 -1.3154444e+00]
 [-4.1600969e-01 -1.5131601e+00 -3.2965709e-02 -2.6238683e-01]
 [-1.1430169e+00 -1.5131601e+00 -2.6031542e-01 -2.6238683e-01]
 [ 9.1683686e-01 -1.3197948e-01  3.6489627e-01  2.6414192e-01]
 [-9.0068120e-01  1.0190043e+00 -1.3402265e+00 -1.3154444e+00]
 [-1.1430169e+00 -1.3197948e-01 -1.3402265e+

Define-se o modelo da rede neural atravez da função mlp:

OBS: Usa-se a função relu pois não se quer trabalhar com números negativos (Ver por que)

OBS2: Softmax não é aplicado na ultima camada, pois a função erro já aplica ela.

In [18]:
def mlp(X, W, bias):
    camada_oculta_entrada = tf.add(tf.matmul(X, W["oculta"]), b["oculta"])
    camada_oculta_ativacao = tf.nn.relu(camada_oculta_entrada)
    camada_saida_entrada = tf.add(tf.matmul(camada_oculta_ativacao, W["saida"]), b["saida"])
    camada_saida_ativacao = tf.nn.softmax(camada_saida_entrada)
    return camada_saida_ativacao

Exemplo do treinamento de uma época:

Utiliza-se o otimizador Adam, que tende a ser melhor do que a descida do gradiente simples

In [19]:
var_list = [W['oculta'], W['saida'], b['oculta'], b['saida']]
otimizador = tf.keras.optimizers.Adam(learning_rate = 0.0001)
erro_medio = 0.0
with tf.GradientTape() as tape:
    model = mlp(X_treinamento, W, b)
    error = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(labels = y_treinamento, logits = model))
gradientes = tape.gradient(error, var_list)
otimizador.apply_gradients(zip(gradientes, var_list))
erro_medio += error.numpy()

erro_medio

np.float32(1.2407862)

Utilizaremos batch size = 8, ou seja, a rede treinara de 8 em 8 registros em X_treinamento

(Passa 8 registros, faz as atualizações dos pesos, passa mais 8, etc...)

São 13 batches de 8 registros cada

In [20]:
batch_size = 8
num_batches = int(len(X_treinamento) / batch_size)

num_batches

13

Agora utiliza-se a função np.array_split para separar os registros do dataset em num_batches arrays (13 arrays), cada um com o mesmo número de registros (8 registros), com exeção do primeiro array que tem 9 registros, pois o numero de registros em X_treinamento e y_treinamento não é divisivel por 8.

In [21]:
X_batches = np.array_split(X_treinamento, num_batches)
y_batches = np.array_split(y_treinamento, num_batches)

In [22]:
X_batches

[array([[ 0.18982966, -0.8225698 ,  0.76275826,  0.5274063 ],
        [-0.53717756,  0.7888076 , -1.1697142 , -1.3154444 ],
        [ 1.6438441 ,  1.249201  ,  1.3311325 ,  1.712096  ],
        [ 1.2803406 ,  0.09821729,  0.9332706 ,  1.1855673 ],
        [-0.17367394, -1.0527666 , -0.14664055, -0.26238683],
        [ 0.795669  , -0.592373  ,  0.47857115,  0.3957741 ],
        [ 2.2496834 , -1.0527666 ,  1.7858319 ,  1.4488316 ],
        [-0.17367394, -0.592373  ,  0.194384  ,  0.13250974],
        [-1.021849  ,  1.249201  , -1.3402265 , -1.3154444 ]],
       dtype=float32),
 array([[-4.1600969e-01, -1.0527666e+00,  3.6489627e-01,  8.7754789e-04],
        [-1.5065205e+00,  1.2492011e+00, -1.5675763e+00, -1.3154444e+00],
        [-4.1600969e-01, -1.5131601e+00, -3.2965709e-02, -2.6238683e-01],
        [-1.1430169e+00, -1.5131601e+00, -2.6031542e-01, -2.6238683e-01],
        [ 9.1683686e-01, -1.3197948e-01,  3.6489627e-01,  2.6414192e-01],
        [-9.0068120e-01,  1.0190043e+00, -1.3402

In [23]:
y_batches

[array([[0., 1., 0.],
        [1., 0., 0.],
        [0., 0., 1.],
        [0., 0., 1.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [0., 1., 0.],
        [1., 0., 0.]], dtype=float32),
 array([[0., 1., 0.],
        [1., 0., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [0., 0., 1.]], dtype=float32),
 array([[1., 0., 0.],
        [0., 0., 1.],
        [1., 0., 0.],
        [1., 0., 0.],
        [0., 0., 1.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 0., 1.]], dtype=float32),
 array([[0., 0., 1.],
        [0., 1., 0.],
        [0., 0., 1.],
        [0., 1., 0.],
        [0., 0., 1.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.]], dtype=float32),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [0., 0., 1.],
        [0., 0., 1.],
        [0., 1., 0.],
        [1., 0., 0.],
        [0., 0., 1.]], dtype=float32),
 array([[0., 

Agora faz-se o treinamento

OBS: zip(A, B) junta cada elemento de A e B em pares para serem iterados.

In [24]:
epochs = 3000

var_list = [W['oculta'], W['saida'], b['oculta'], b['saida']]
otimizador = tf.keras.optimizers.Adam(learning_rate = 0.0001)

for epoch in range(epochs):
    erro_medio = 0.0
    for i in range(num_batches):
        X_batch, y_batch = X_batches[i], y_batches[i]
        with tf.GradientTape() as tape:
            model = mlp(X_batch, W, b)
            error = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(labels = y_batch, logits = model))
        gradientes = tape.gradient(error, var_list)
        otimizador.apply_gradients(zip(gradientes, var_list))
        erro_medio += error.numpy()
    
    if epoch % 500 == 0:
        print('Época: ' + str((epoch + 1)) + ' erro: ' + str(erro_medio))


Época: 1 erro: 16.116638
Época: 501 erro: 10.432567


KeyboardInterrupt: 

Utiliza-se softmax na ultima camada para converte-la em um vetor de probabilidades, cada um dos 4 neuronios terá uma probabilidade associada a entrada ser de uma das 4 classes do dataset.

In [27]:
import tensorflow as tf

print("TF version:", tf.__version__)
print("GPUs:", tf.config.list_physical_devices('GPU'))


TF version: 2.20.0
GPUs: []
