In [108]:
import tensorflow as tf

Obs: Multiplcação faz a operação da seguinte forma:
a = [a1, a2, a3, ... , an], b = [b1, b2, b3, ... , bn]

tf.multiply(a, b) faz:

[a1 * b1, a2 * b2, a3 * b3 , ... , an * bn].

In [109]:
a = tf.constant([[-1.0, 7.0, 5.0]], name = 'entradas')
b = tf.constant([[0.8, 0.1, 0.0]], name = 'pesos')

multiplicacao = tf.multiply(a, b)
soma = tf.reduce_sum(multiplicacao)

Tentar fazer a multiplicação entre inteiros e floats retorna um erro:

In [110]:
a = tf.constant([[1.0, 2.0, 3.0]], name = 'entradas')
b = tf.constant([[4, 5, 6]], name = 'pesos')

try:
    mult = tf.multiply(a, b)
except Exception as e:
    print(e)

cannot compute Mul as input #1(zero-based) was expected to be a float tensor but is a int32 tensor [Op:Mul]


In [111]:
b = tf.constant([[4.0, 5.0, 6.0]], name = 'pesos')

mult = tf.multiply(a, b)
print(mult)

tf.Tensor([[ 4. 10. 18.]], shape=(1, 3), dtype=float32)


Tentar fazer multiplicação de objetos de tamanhos incompativeis retorna um erro:

In [112]:
b = tf.constant([[4.0, 5.0, 6.0, 7.0]], name = 'pesos')

try:
    mult = tf.multiply(a, b)
except Exception as e:
    print(e)

Incompatible shapes: [1,3] vs. [1,4] [Op:Mul]


tf.reduce_sum faz o produto escalar entre dois vetores.
Ou seja:

sum = [a1, a2, a3, ... , an] = a1 + a2 + a3 + ... + an

Nesse caso, sum = 4 + 5 + 6 = 15.

In [113]:
b = tf.constant([[4.0, 5.0, 6.0]], name = 'pesos')
sum = tf.reduce_sum(b)
sum

<tf.Tensor: shape=(), dtype=float32, numpy=15.0>

In [114]:
b = tf.constant([[0.8, 0.1, 0.0]], name = 'pesos')
print(a)
print('\n')
print(b)
print('\n')
print(multiplicacao)
print('\n')
print(soma)

tf.Tensor([[1. 2. 3.]], shape=(1, 3), dtype=float32)


tf.Tensor([[0.8 0.1 0. ]], shape=(1, 3), dtype=float32)


tf.Tensor([[-0.8  0.7  0. ]], shape=(1, 3), dtype=float32)


tf.Tensor(-0.100000024, shape=(), dtype=float32)
