In [1]:
numero = 2

vetor = [2, 3, 5]

In [2]:
import numpy as np
vetor = np.asarray(vetor)

In [ ]:
#Retorna o maior valor em vetor

vetor.max()

np.int64(5)

In [ ]:
#Retorna o índice do maior valor em vetor

vetor.argmax()

np.int64(2)

In [ ]:
#Retorna o menor valor em vetor

vetor.min()

np.int64(2)

In [ ]:
#Retorna a média dos elementos em vetor

vetor.mean()

np.float64(3.3333333333333335)

In [ ]:
#Retorna a soma dos elementos em vetor

vetor.sum()

np.int64(10)

In [ ]:
#Cria um novo array como: vetor2[i] = numero * vetor[i]

vetor2 = numero * vetor

vetor2

array([ 4,  6, 10])

In [ ]:
#Cria um array com todos os elementos sendo floats entre 1 e 50
#Com incremento de 0.5, e 50 excluído

np.arange(1, 50, 0.5)

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5, 11. , 11.5,
       12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. , 16.5, 17. ,
       17.5, 18. , 18.5, 19. , 19.5, 20. , 20.5, 21. , 21.5, 22. , 22.5,
       23. , 23.5, 24. , 24.5, 25. , 25.5, 26. , 26.5, 27. , 27.5, 28. ,
       28.5, 29. , 29.5, 30. , 30.5, 31. , 31.5, 32. , 32.5, 33. , 33.5,
       34. , 34.5, 35. , 35.5, 36. , 36.5, 37. , 37.5, 38. , 38.5, 39. ,
       39.5, 40. , 40.5, 41. , 41.5, 42. , 42.5, 43. , 43.5, 44. , 44.5,
       45. , 45.5, 46. , 46.5, 47. , 47.5, 48. , 48.5, 49. , 49.5])

In [ ]:
#Cria um array com 10 elementos, todos sendo 0 (Float)

np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
#Cria uma matrix 3x3, com todos os elementos sendo 0 (Float)

np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
#Cria um array com 10 elementos, todos sendo 1 (Float)


np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
#Cria uma matrix 3x3, com todos os elementos sendo 1 (Float)

np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
#Cria um array com 5 elementos espaçados igualmente entre 1 e 20

np.linspace(1, 20, 5)

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])

In [15]:
np.random.seed(1)

In [ ]:
#Cria um array com 4 elementos aleatórios de 0 a 101

np.random.randint(0, 101, 4)

array([37, 12, 72,  9], dtype=int32)

In [ ]:
#Cria uma matrix 3x3 com elementos aleatórios de 0 a 101

np.random.randint(0, 101, (3,3))

array([[75,  5, 79],
       [64, 16,  1],
       [76, 71,  6]], dtype=int32)