In [1]:
import pandas as pd
base = pd.read_csv('house_prices.csv')
base.head()

id             date     price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000  221900.0         3       1.00         1180   
1  6414100192  20141209T000000  538000.0         3       2.25         2570   
2  5631500400  20150225T000000  180000.0         2       1.00          770   
3  2487200875  20141209T000000  604000.0         4       3.00         1960   
4  1954400510  20150218T000000  510000.0         3       2.00         1680   

   sqft_lot  floors  waterfront  view  ...  grade  sqft_above  sqft_basement  \
0      5650     1.0           0     0  ...      7        1180              0   
1      7242     2.0           0     0  ...      7        2170            400   
2     10000     1.0           0     0  ...      6         770              0   
3      5000     1.0           0     0  ...      7        1050            910   
4      8080     1.0           0     0  ...      8        1680              0   

   yr_built  yr_renovated  zipcode      lat     long  sqft_living15  \
0      1955             0    98178  47.5112 -122.257           1340   
1      1951          1991    98125  47.7210 -122.319           1690   
2      1933             0    98028  47.7379 -122.233           2720   
3      1965             0    98136  47.5208 -122.393           1360   
4      1987             0    98074  47.6168 -122.045           1800   

   sqft_lot15  
0        5650  
1        7639  
2        8062  
3        5000  
4        7503  

[5 rows x 21 columns]

In [2]:
base.columns

Index(['id', 'date', 'price', 'bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long', 'sqft_living15', 'sqft_lot15'],
      dtype='object')

In [3]:
colunas_usadas = ['price', 'bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long']

In [4]:
colunas_usadas

['price',
 'bedrooms',
 'bathrooms',
 'sqft_living',
 'sqft_lot',
 'floors',
 'waterfront',
 'view',
 'condition',
 'grade',
 'sqft_above',
 'sqft_basement',
 'yr_built',
 'yr_renovated',
 'zipcode',
 'lat',
 'long']

In [5]:
base = pd.read_csv('house_prices.csv', usecols = colunas_usadas)

In [6]:
base.head()

price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  \
0  221900.0         3       1.00         1180      5650     1.0           0   
1  538000.0         3       2.25         2570      7242     2.0           0   
2  180000.0         2       1.00          770     10000     1.0           0   
3  604000.0         4       3.00         1960      5000     1.0           0   
4  510000.0         3       2.00         1680      8080     1.0           0   

   view  condition  grade  sqft_above  sqft_basement  yr_built  yr_renovated  \
0     0          3      7        1180              0      1955             0   
1     0          3      7        2170            400      1951          1991   
2     0          3      6         770              0      1933             0   
3     0          5      7        1050            910      1965             0   
4     0          3      8        1680              0      1987             0   

   zipcode      lat     long  
0    98178  47.5112 -122.257  
1    98125  47.7210 -122.319  
2    98028  47.7379 -122.233  
3    98136  47.5208 -122.393  
4    98074  47.6168 -122.045

In [7]:
from sklearn.preprocessing import MinMaxScaler
scaler_x = MinMaxScaler()
base[['bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long']] = scaler_x.fit_transform(base[['bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long']])

In [8]:
base.head()

price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  \
0  221900.0  0.090909    0.12500     0.067170  0.003108     0.0         0.0   
1  538000.0  0.090909    0.28125     0.172075  0.004072     0.4         0.0   
2  180000.0  0.060606    0.12500     0.036226  0.005743     0.0         0.0   
3  604000.0  0.121212    0.37500     0.126038  0.002714     0.0         0.0   
4  510000.0  0.090909    0.25000     0.104906  0.004579     0.0         0.0   

   view  condition     grade  sqft_above  sqft_basement  yr_built  \
0   0.0        0.5  0.500000    0.097588       0.000000  0.478261   
1   0.0        0.5  0.500000    0.206140       0.082988  0.443478   
2   0.0        0.5  0.416667    0.052632       0.000000  0.286957   
3   0.0        1.0  0.500000    0.083333       0.188797  0.565217   
4   0.0        0.5  0.583333    0.152412       0.000000  0.756522   

   yr_renovated   zipcode       lat      long  
0      0.000000  0.893939  0.571498  0.217608  
1      0.988089  0.626263  0.908959  0.166113  
2      0.000000  0.136364  0.936143  0.237542  
3      0.000000  0.681818  0.586939  0.104651  
4      0.000000  0.368687  0.741354  0.393688

In [9]:
scaler_y = MinMaxScaler()
base[['price']] = scaler_y.fit_transform(base[['price']])

In [10]:
base.head()

price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  \
0  0.019266  0.090909    0.12500     0.067170  0.003108     0.0         0.0   
1  0.060721  0.090909    0.28125     0.172075  0.004072     0.4         0.0   
2  0.013770  0.060606    0.12500     0.036226  0.005743     0.0         0.0   
3  0.069377  0.121212    0.37500     0.126038  0.002714     0.0         0.0   
4  0.057049  0.090909    0.25000     0.104906  0.004579     0.0         0.0   

   view  condition     grade  sqft_above  sqft_basement  yr_built  \
0   0.0        0.5  0.500000    0.097588       0.000000  0.478261   
1   0.0        0.5  0.500000    0.206140       0.082988  0.443478   
2   0.0        0.5  0.416667    0.052632       0.000000  0.286957   
3   0.0        1.0  0.500000    0.083333       0.188797  0.565217   
4   0.0        0.5  0.583333    0.152412       0.000000  0.756522   

   yr_renovated   zipcode       lat      long  
0      0.000000  0.893939  0.571498  0.217608  
1      0.988089  0.626263  0.908959  0.166113  
2      0.000000  0.136364  0.936143  0.237542  
3      0.000000  0.681818  0.586939  0.104651  
4      0.000000  0.368687  0.741354  0.393688

In [11]:
X = base.drop('price', axis = 1)
y = base.price

In [12]:
X.head()

bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  view  \
0  0.090909    0.12500     0.067170  0.003108     0.0         0.0   0.0   
1  0.090909    0.28125     0.172075  0.004072     0.4         0.0   0.0   
2  0.060606    0.12500     0.036226  0.005743     0.0         0.0   0.0   
3  0.121212    0.37500     0.126038  0.002714     0.0         0.0   0.0   
4  0.090909    0.25000     0.104906  0.004579     0.0         0.0   0.0   

   condition     grade  sqft_above  sqft_basement  yr_built  yr_renovated  \
0        0.5  0.500000    0.097588       0.000000  0.478261      0.000000   
1        0.5  0.500000    0.206140       0.082988  0.443478      0.988089   
2        0.5  0.416667    0.052632       0.000000  0.286957      0.000000   
3        1.0  0.500000    0.083333       0.188797  0.565217      0.000000   
4        0.5  0.583333    0.152412       0.000000  0.756522      0.000000   

    zipcode       lat      long  
0  0.893939  0.571498  0.217608  
1  0.626263  0.908959  0.166113  
2  0.136364  0.936143  0.237542  
3  0.681818  0.586939  0.104651  
4  0.368687  0.741354  0.393688

In [13]:
type(X)

pandas.core.frame.DataFrame

In [14]:
y.head()

0    0.019266
1    0.060721
2    0.013770
3    0.069377
4    0.057049
Name: price, dtype: float64

In [15]:
type(y)

pandas.core.series.Series

In [16]:
previsores_colunas = colunas_usadas[1:17]
previsores_colunas

['bedrooms',
 'bathrooms',
 'sqft_living',
 'sqft_lot',
 'floors',
 'waterfront',
 'view',
 'condition',
 'grade',
 'sqft_above',
 'sqft_basement',
 'yr_built',
 'yr_renovated',
 'zipcode',
 'lat',
 'long']

In [17]:
import tensorflow as tf

/home/ariel/anaconda3/envs/curso-tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/ariel/anaconda3/envs/curso-tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/ariel/anaconda3/envs/curso-tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/ariel/anacond

In [18]:
#Cria uma lista de colunas que serão usadas como previsores. a partir da lista de colunas usadas (que são strings)
colunas = [tf.feature_column.numeric_column(key = c) for c in previsores_colunas]

In [19]:
print(colunas[10])

NumericColumn(key='sqft_basement', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None)


In [20]:
#Separa a base de dados em treinamento e teste de forma que 70% dos dados serão usados para treinamento e 30% para teste
from sklearn.model_selection import train_test_split
X_treinamento, X_teste, y_treinamento, y_teste = train_test_split(X, y, test_size = 0.3)

In [21]:
X_treinamento.shape

(15129, 16)

In [22]:
y_treinamento.shape

(15129,)

In [23]:
X_teste.shape

(6484, 16)

In [24]:
#Prepara a estrutura que feedará o modelo com os dados de treinamento
#num_epochs = None é para ue o modelo treine até que o erro seja minimizado.
#shuffle = True é para que os dados sejam embaralhados a cada epoch
funcao_treinamento = tf.estimator.inputs.pandas_input_fn(x = X_treinamento, y = y_treinamento,
                                                        batch_size = 32, num_epochs = None, shuffle = True)

In [25]:
#Prepara a estrutura que feedará o modelo com os dados de teste
#num_epochs = 10000 é para que o modelo treine 10000 vezes em cima dos dados de teste
#shuffle = False é para que os dados não sejam embaralhados
funcao_teste = tf.estimator.inputs.pandas_input_fn(x = X_teste, y = y_teste,
                                                   batch_size = 32, num_epochs = 10000, shuffle = False)

In [26]:
#Cria o estimator que usa regressor linear e o prepara para lidar com as colunas que foram criadas
regressor = tf.estimator.LinearRegressor(feature_columns=colunas)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': '/tmp/tmprvsu2aub', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7ff5afe35ef0>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}


In [27]:
#O estimator é feedado com os dados de treinamento a partir da estrutura funcao_treinamento e realiza o treino internamente provavelmente usando SGE para minimizar o erro
#(Stochastic Gradient Descent)
regressor.train(input_fn=funcao_treinamento, steps = 10000)

Instructions for updating:
Use Variable.read_value. Variables in 2.X are initialized automatically both in eager and graph (inside tf.defun) contexts.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
INFO:tensorflow:Calling model_fn.
Instructions for updating:
Use `tf.cast` instead.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
INFO:tensorflow:Saving checkpoints for 0 into /tmp/tmprvsu2aub/model.ckpt.
INFO:tensorflow:loss = 0.17012173, step = 1
INFO:tensorflow:global_step/sec: 203.619
INFO:tensorflow:loss = 0.01455813, step = 101 (0.496 sec)
I

In [28]:
#O estimator é feedado com os dados de teste a partir da estrutura funcao_teste e é então avaliado a partir delas
metricas_treinamento = regressor.evaluate(input_fn=funcao_treinamento, steps = 10000)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2024-02-07T04:00:45Z
INFO:tensorflow:Graph was finalized.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
INFO:tensorflow:Restoring parameters from /tmp/tmprvsu2aub/model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Evaluation [1000/10000]
INFO:tensorflow:Evaluation [2000/10000]
INFO:tensorflow:Evaluation [3000/10000]
INFO:tensorflow:Evaluation [4000/10000]
INFO:tensorflow:Evaluation [5000/10000]
INFO:tensorflow:Evaluation [6000/10000]
INFO:tensorflow:Evaluation [7000/10000]
INFO:tensorflow:Evaluation [8000/10000]
INFO:tensorflow:Evaluation [9000/10000]
INFO:tensorflow:Evaluation [10000/10000]
INFO:tensorflow:Finished evaluation at 2024-02-07-04:01:14
INFO:tensorflow:Saving dict for global step 10000: average_loss = 0.0007152189, global_step = 10000, label/mean = 0.06083923

In [29]:
#O estimator é feedado com os dados de teste a partir da estrutura funcao_teste e é então avaliado a partir delas
#Aparentemente ele não guarda os dados internamente, pois posteriormente ele precisa ser realimentado para que então possa fazer previsões arbitrárias
metricas_teste = regressor.evaluate(input_fn=funcao_teste, steps = 10000)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2024-02-07T04:01:16Z
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /tmp/tmprvsu2aub/model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Evaluation [1000/10000]
INFO:tensorflow:Evaluation [2000/10000]
INFO:tensorflow:Evaluation [3000/10000]
INFO:tensorflow:Evaluation [4000/10000]
INFO:tensorflow:Evaluation [5000/10000]
INFO:tensorflow:Evaluation [6000/10000]
INFO:tensorflow:Evaluation [7000/10000]
INFO:tensorflow:Evaluation [8000/10000]
INFO:tensorflow:Evaluation [9000/10000]
INFO:tensorflow:Evaluation [10000/10000]
INFO:tensorflow:Finished evaluation at 2024-02-07-04:01:47
INFO:tensorflow:Saving dict for global step 10000: average_loss = 0.00078505353, global_step = 10000, label/mean = 0.0613467, loss = 0.025121713, prediction/mean = 0.06489583
INFO:tensorflow:Saving 'checkpoint_p

In [30]:
metricas_treinamento

{'average_loss': 0.0007152189,
 'label/mean': 0.060839232,
 'loss': 0.022887005,
 'prediction/mean': 0.06449095,
 'global_step': 10000}

In [31]:
metricas_teste

{'average_loss': 0.00078505353,
 'label/mean': 0.0613467,
 'loss': 0.025121713,
 'prediction/mean': 0.06489583,
 'global_step': 10000}

In [32]:
#Prepara a estrutura que feedará o modelo com os dados de teste para realizar previsões arbitrarias
funcao_previsao = tf.estimator.inputs.pandas_input_fn(x = X_teste, shuffle = False)

In [33]:
#Usa o estimator para realizar previsões a partir dos dados de teste que foram feedados a ele pela estrutura funcao_previsao e atribui o resultado a previsoes
#Nesse momento, provavelmente o estimator aprendeu os coeficientes da regressão linear e precisa receber os dados para realizar previsões em cima deles
#Já que ele não guarda os dados internamente dos outros passos
previsoes = regressor.predict(input_fn=funcao_previsao)

In [34]:
list(previsoes)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /tmp/tmprvsu2aub/model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


[{'predictions': array([0.05875956], dtype=float32)},
 {'predictions': array([0.04279197], dtype=float32)},
 {'predictions': array([0.03592145], dtype=float32)},
 {'predictions': array([0.04580619], dtype=float32)},
 {'predictions': array([0.05741882], dtype=float32)},
 {'predictions': array([0.04587484], dtype=float32)},
 {'predictions': array([0.08284127], dtype=float32)},
 {'predictions': array([0.0558323], dtype=float32)},
 {'predictions': array([0.06295603], dtype=float32)},
 {'predictions': array([0.05222533], dtype=float32)},
 {'predictions': array([0.07906585], dtype=float32)},
 {'predictions': array([0.10347254], dtype=float32)},
 {'predictions': array([0.04923444], dtype=float32)},
 {'predictions': array([0.0220741], dtype=float32)},
 {'predictions': array([0.04316048], dtype=float32)},
 {'predictions': array([0.08348755], dtype=float32)},
 {'predictions': array([0.14144918], dtype=float32)},
 {'predictions': array([0.06659388], dtype=float32)},
 {'predictions': array([-0.000

In [35]:
valores_previsoes = []

#Popula a lista valores_previsoes com as previsões realizadas pelo estimator a partir dos dados de teste feedados a ele pela estrutura funcao_previsao
for p in regressor.predict(input_fn=funcao_previsao):
    valores_previsoes.append(p['predictions'])

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /tmp/tmprvsu2aub/model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


In [36]:
valores_previsoes

[array([0.05875956], dtype=float32),
 array([0.04279197], dtype=float32),
 array([0.03592145], dtype=float32),
 array([0.04580619], dtype=float32),
 array([0.05741882], dtype=float32),
 array([0.04587484], dtype=float32),
 array([0.08284127], dtype=float32),
 array([0.0558323], dtype=float32),
 array([0.06295603], dtype=float32),
 array([0.05222533], dtype=float32),
 array([0.07906585], dtype=float32),
 array([0.10347254], dtype=float32),
 array([0.04923444], dtype=float32),
 array([0.0220741], dtype=float32),
 array([0.04316048], dtype=float32),
 array([0.08348755], dtype=float32),
 array([0.14144918], dtype=float32),
 array([0.06659388], dtype=float32),
 array([-0.00094739], dtype=float32),
 array([0.05298402], dtype=float32),
 array([0.0526009], dtype=float32),
 array([0.04841233], dtype=float32),
 array([0.07340113], dtype=float32),
 array([0.06853183], dtype=float32),
 array([0.20697865], dtype=float32),
 array([0.07159177], dtype=float32),
 array([0.02805858], dtype=float32),
 ar

In [47]:
#Contem 6484 linhas e 1 coluna
valores_previsoes.shape

(6484, 1)

In [49]:
type(valores_previsoes)

numpy.ndarray

In [37]:
import numpy as np

#Transforma a lista valores_previsoes em um array
#reshape(-1,1) é para que o array seja transformado em um array de uma coluna
#o -1 é para que o numpy entenda que o número de linhas é o número de elementos da lista
#o 1 é para que o numpy entenda que o número de colunas é 1
#Ou seja é como se "empilhase" tudo em uma única dimensão que é a coluna com todos os dados

#OBS: Não entendi para que isso é necessário, se valoes_previsoes já é um array já tem esse shape.
valores_previsoes = np.asarray(valores_previsoes).reshape(-1,1)

In [38]:
valores_previsoes

array([[0.05875956],
       [0.04279197],
       [0.03592145],
       ...,
       [0.05316746],
       [0.04000767],
       [0.02154601]], dtype=float32)

In [48]:
valores_previsoes.shape

(6484, 1)

In [50]:
type(valores_previsoes)

numpy.ndarray

In [39]:
#Aplica o desescalonamento nos valores de previsões
valores_previsoes = scaler_y.inverse_transform(valores_previsoes)
valores_previsoes

array([[523041.66],
       [401288.78],
       [348901.1 ],
       ...,
       [480401.88],
       [380058.47],
       [239288.36]], dtype=float32)

In [40]:
#Váriavel que contém os preços reais dos imóveis (30% deles), porém escalonados
y_teste

7993     0.035016
15088    0.042216
12912    0.032918
16471    0.034754
19237    0.030295
           ...   
17384    0.029115
11156    0.054413
9766     0.055607
13925    0.053770
7110     0.021639
Name: price, Length: 6484, dtype: float64

In [41]:
#Contém 6484 linhas e nenhuma coluna, ou seja é um array de uma dimensão (uma lista comúm com 6484 elementos)
y_teste.shape

(6484,)

In [42]:
#Transforma a lista y_teste em um array de uma coluna
# o -1 é para que o numpy entenda que o número de linhas é o número de elementos da lista, e o 1 é para que o numpy entenda que o número de colunas é 1
y_teste2 = y_teste.values.reshape(-1,1)
y_teste2.shape

(6484, 1)

In [43]:
#Aplica o desescalonamento nos valores de preços reais
y_teste2 = scaler_y.inverse_transform(y_teste2)

In [44]:
y_teste2

array([[342000.],
       [396900.],
       [326000.],
       ...,
       [499000.],
       [485000.],
       [240000.]])

In [45]:
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_teste2, valores_previsoes)

In [46]:
mae

132326.73541321894